### ISSUE TITLE
暗号と認証のしくみと理論がこれ1冊でしっかりわかる教科書

### ISSUE THREAD

**Issue by yoshioH** [dokurin/toy-box#17]
https://www.amazon.co.jp/dp/429712307X

**Comment by ryutah** [comment]
[暗号技術入門 第3版　秘密の国のアリス Kindle版](https://www.amazon.co.jp/%E6%9A%97%E5%8F%B7%E6%8A%80%E8%A1%93%E5%85%A5%E9%96%80-%E7%AC%AC3%E7%89%88-%E7%A7%98%E5%AF%86%E3%81%AE%E5%9B%BD%E3%81%AE%E3%82%A2%E3%83%AA%E3%82%B9-%E7%B5%90%E5%9F%8E-%E6%B5%A9-ebook/dp/B015643CPE) こっちもいいかも？
