### ISSUE TITLE
計算できるもの、計算できないもの

### ISSUE THREAD

**Issue by yoshioH** [dokurin/toy-box#34]
[計算できるもの、計算できないもの ―実践的アプローチによる計算理論入門](https://www.amazon.co.jp/%E8%A8%88%E7%AE%97%E3%81%A7%E3%81%8D%E3%82%8B%E3%82%82%E3%81%AE%E3%80%81%E8%A8%88%E7%AE%97%E3%81%A7%E3%81%8D%E3%81%AA%E3%81%84%E3%82%82%E3%81%AE-%E2%80%95%E5%AE%9F%E8%B7%B5%E7%9A%84%E3%82%A2%E3%83%97%E3%83%AD%E3%83%BC%E3%83%81%E3%81%AB%E3%82%88%E3%82%8B%E8%A8%88%E7%AE%97%E7%90%86%E8%AB%96%E5%85%A5%E9%96%80-John-MacCormick/dp/4873119332/ref=sr_1_1?__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&crid=2RLB04764FDJ4&dchild=1&keywords=%E8%A8%88%E7%AE%97%E3%81%A7%E3%81%8D%E3%82%8B%E3%82%82%E3%81%AE+%E8%A8%88%E7%AE%97%E3%81%A7%E3%81%8D%E3%81%AA%E3%81%84%E3%82%82%E3%81%AE&qid=1633160122&s=books&sprefix=%E8%A8%88%E7%AE%97%E3%81%A7%E3%81%8D%E3%82%8B%E3%82%82%E3%81%AE%2Cstripbooks%2C251&sr=1-1)

**Comment by ryutah** [comment]
move to https://github.com/dokurin/toy-box/discussions/37#discussioncomment-1417755
